baseURL = 'https://mariachiaraferraiuolo.github.io/'
languageCode = 'en-us'
title = 'Mariachiara Ferraiuolo'
theme = 'Hextra'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2